import React, { useState, useEffect } from 'react';
import {
  Bell,
  AlertTriangle,
  CheckCircle2,
  Calendar,
  Check,
  ArrowRight,
} from 'lucide-react';
import { useTranslation } from '../hooks/useTranslation';
import { alertsApi } from '../api/client';
import { Alert } from '../types';

interface AlertsPageProps {
  onNavigate: (tab: string) => void;
}

export const AlertsPage: React.FC<AlertsPageProps> = ({ onNavigate }) => {
  const { t } = useTranslation();

  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const [isLoading, setIsLoading] = useState(true);

  const loadAlerts = async () => {
    try {
      const res = await alertsApi.list();
      setAlerts(res.alerts);
    } catch {
      // Fallback
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const handleMarkRead = async (id: number) => {
    try {
      await alertsApi.markRead(id);
      setAlerts((prev) =>
        prev.map((a) => (a.id === id ? { ...a, is_read: true } : a))
      );
    } catch (err) {
      console.error('Failed to mark read', err);
    }
  };

  const displayedAlerts = alerts.filter((a) => {
    if (filter === 'unread') return !a.is_read;
    return true;
  });

  return (
    <div className="space-y-6 max-w-4xl">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <span>Crop Health Early Warning Alerts</span>
            <span className="text-xs font-semibold px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
              Active Monitoring
            </span>
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Real-time notifications generated by satellite NDVI stress drops, drone scans, and leaf pathology.
          </p>
        </div>

        {/* Unread Filter */}
        <div className="flex items-center gap-1.5 p-1 rounded-xl bg-slate-900 border border-slate-800 text-xs">
          <button
            onClick={() => setFilter('all')}
            className={`px-3 py-1.5 rounded-lg transition ${
              filter === 'all' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'
            }`}
          >
            All ({alerts.length})
          </button>
          <button
            onClick={() => setFilter('unread')}
            className={`px-3 py-1.5 rounded-lg transition ${
              filter === 'unread' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'
            }`}
          >
            Unread ({alerts.filter((a) => !a.is_read).length})
          </button>
        </div>
      </div>

      <div className="space-y-3">
        {displayedAlerts.length > 0 ? (
          displayedAlerts.map((alert) => (
            <div
              key={alert.id}
              className={`p-4 rounded-2xl glass-card border transition ${
                !alert.is_read ? 'border-amber-500/40 bg-amber-950/10' : 'border-slate-800/80 opacity-80'
              }`}
            >
              <div className="flex items-start justify-between gap-3 mb-2">
                <div className="flex items-center gap-2.5">
                  <div className={`p-2 rounded-xl ${
                    alert.severity === 'critical' ? 'bg-rose-500/20 text-rose-400' :
                    alert.severity === 'high' ? 'bg-amber-500/20 text-amber-400' :
                    'bg-cyan-500/20 text-cyan-400'
                  }`}>
                    <AlertTriangle className="w-4 h-4" />
                  </div>
                  <div>
                    <h3 className="font-bold text-white text-sm">{alert.title}</h3>
                    <div className="flex items-center gap-2 text-[11px] text-slate-400 mt-0.5">
                      <Calendar className="w-3 h-3" />
                      <span>{new Date(alert.created_at).toLocaleString()}</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <span className={`text-[10px] font-bold px-2.5 py-0.5 rounded-full uppercase tracking-wider ${
                    alert.severity === 'critical' ? 'bg-rose-500/20 text-rose-400 border border-rose-500/30' :
                    alert.severity === 'high' ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' :
                    'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30'
                  }`}>
                    {alert.severity}
                  </span>

                  {!alert.is_read && (
                    <button
                      onClick={() => handleMarkRead(alert.id)}
                      className="p-1.5 rounded-lg bg-slate-900 hover:bg-emerald-500/20 text-slate-400 hover:text-emerald-400 border border-slate-700 transition"
                      title="Mark as read"
                    >
                      <Check className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>
              </div>

              <p className="text-xs text-slate-300 pl-11 leading-relaxed">
                {alert.message}
              </p>

              <div className="mt-3 pl-11 flex items-center gap-3">
                <button
                  onClick={() => onNavigate('risk-map')}
                  className="text-xs font-semibold text-emerald-400 hover:underline flex items-center gap-1"
                >
                  <span>View Field Risk Map</span>
                  <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>
          ))
        ) : (
          <div className="glass-panel rounded-2xl p-8 border border-slate-800 text-center">
            <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto mb-2" />
            <h3 className="font-bold text-white text-base">All Clear!</h3>
            <p className="text-xs text-slate-400 mt-1">No pending alerts requiring attention.</p>
          </div>
        )}
      </div>
    </div>
  );
};
